//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorWorx.Designer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DesignerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndoorWorx.Designer.Resources.DesignerResources", typeof(DesignerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string CatalogPaneTitle {
            get {
                return ResourceManager.GetString("CatalogPaneTitle", resourceCulture);
            }
        }
        
        public static byte[] Design {
            get {
                object obj = ResourceManager.GetObject("Design", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string DesignPaneTitle {
            get {
                return ResourceManager.GetString("DesignPaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading media ....
        /// </summary>
        public static string LoadingMediaProgressMessage {
            get {
                return ResourceManager.GetString("LoadingMediaProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading telemetry ....
        /// </summary>
        public static string LoadingTelemetryProgressMessage {
            get {
                return ResourceManager.GetString("LoadingTelemetryProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Library.
        /// </summary>
        public static string MyLibraryPaneTitle {
            get {
                return ResourceManager.GetString("MyLibraryPaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design New Training Set.
        /// </summary>
        public static string NewDesignTitle {
            get {
                return ResourceManager.GetString("NewDesignTitle", resourceCulture);
            }
        }
        
        public static byte[] Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewPaneTitle {
            get {
                return ResourceManager.GetString("PreviewPaneTitle", resourceCulture);
            }
        }
        
        public static byte[] Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry.
        /// </summary>
        public static string TelemetryTitle {
            get {
                return ResourceManager.GetString("TelemetryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Metrics.
        /// </summary>
        public static string TrainingMetricsTitle {
            get {
                return ResourceManager.GetString("TrainingMetricsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Sets.
        /// </summary>
        public static string TrainingSetsTitle {
            get {
                return ResourceManager.GetString("TrainingSetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown item type {0}.
        /// </summary>
        public static string UnknownItemTypeErrorMessage {
            get {
                return ResourceManager.GetString("UnknownItemTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use in designer ....
        /// </summary>
        public static string UseSelectedTrainingSetMenuItem {
            get {
                return ResourceManager.GetString("UseSelectedTrainingSetMenuItem", resourceCulture);
            }
        }
        
        public static byte[] ZoomIn {
            get {
                object obj = ResourceManager.GetObject("ZoomIn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ZoomOut {
            get {
                object obj = ResourceManager.GetObject("ZoomOut", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
