//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorWorx.Designer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DesignerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndoorWorx.Designer.Resources.DesignerResources", typeof(DesignerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY INTERVAL.
        /// </summary>
        public static string ByIntervalLabel {
            get {
                return ResourceManager.GetString("ByIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY SET.
        /// </summary>
        public static string BySetLabel {
            get {
                return ResourceManager.GetString("BySetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM.
        /// </summary>
        public static string FromLabel {
            get {
                return ResourceManager.GetString("FromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOMMENDED VIDEOS.
        /// </summary>
        public static string RecommendedVideosLabel {
            get {
                return ResourceManager.GetString("RecommendedVideosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new ride design.
        /// </summary>
        public static string RideDesignTitle {
            get {
                return ResourceManager.GetString("RideDesignTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This video is too short to be used for this interval..
        /// </summary>
        public static string SelectedVideoIsTooShortForInterval {
            get {
                return ResourceManager.GetString("SelectedVideoIsTooShortForInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This video is too short to be used for this group of intervals..
        /// </summary>
        public static string SelectedVideoIsTooShortForIntervalGroup {
            get {
                return ResourceManager.GetString("SelectedVideoIsTooShortForIntervalGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This video is too short to be used for this template..
        /// </summary>
        public static string SelectedVideoIsTooShortForTemplate {
            get {
                return ResourceManager.GetString("SelectedVideoIsTooShortForTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETS.
        /// </summary>
        public static string SetsLabel {
            get {
                return ResourceManager.GetString("SetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPLATE.
        /// </summary>
        public static string TemplateLabel {
            get {
                return ResourceManager.GetString("TemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO.
        /// </summary>
        public static string ToLabel {
            get {
                return ResourceManager.GetString("ToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE MULTIPLE VIDEOS.
        /// </summary>
        public static string UseMultipleVideosLabel {
            get {
                return ResourceManager.GetString("UseMultipleVideosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE SINGLE VIDEO.
        /// </summary>
        public static string UseSingleVideoLabel {
            get {
                return ResourceManager.GetString("UseSingleVideoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEOS IN YOUR LIBRARY.
        /// </summary>
        public static string VideosInYourLibraryLabel {
            get {
                return ResourceManager.GetString("VideosInYourLibraryLabel", resourceCulture);
            }
        }
    }
}
