//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace IndoorWorx.Library.SocialMediaServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SocialMediaServiceReference.ISocialMediaService")]
    public interface ISocialMediaService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISocialMediaService/RetrieveSocialMediaTypes", ReplyAction="http://tempuri.org/ISocialMediaService/RetrieveSocialMediaTypesResponse")]
        System.IAsyncResult BeginRetrieveSocialMediaTypes(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaType> EndRetrieveSocialMediaTypes(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISocialMediaService/SocialMediaNotificationOptions", ReplyAction="http://tempuri.org/ISocialMediaService/SocialMediaNotificationOptionsResponse")]
        System.IAsyncResult BeginSocialMediaNotificationOptions(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaNotification> EndSocialMediaNotificationOptions(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocialMediaServiceChannel : IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveSocialMediaTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveSocialMediaTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaType> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaType>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocialMediaNotificationOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SocialMediaNotificationOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaNotification> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaNotification>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocialMediaServiceClient : System.ServiceModel.ClientBase<IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService>, IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService {
        
        private BeginOperationDelegate onBeginRetrieveSocialMediaTypesDelegate;
        
        private EndOperationDelegate onEndRetrieveSocialMediaTypesDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveSocialMediaTypesCompletedDelegate;
        
        private BeginOperationDelegate onBeginSocialMediaNotificationOptionsDelegate;
        
        private EndOperationDelegate onEndSocialMediaNotificationOptionsDelegate;
        
        private System.Threading.SendOrPostCallback onSocialMediaNotificationOptionsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SocialMediaServiceClient() {
        }
        
        public SocialMediaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocialMediaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialMediaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialMediaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RetrieveSocialMediaTypesCompletedEventArgs> RetrieveSocialMediaTypesCompleted;
        
        public event System.EventHandler<SocialMediaNotificationOptionsCompletedEventArgs> SocialMediaNotificationOptionsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService.BeginRetrieveSocialMediaTypes(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveSocialMediaTypes(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaType> IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService.EndRetrieveSocialMediaTypes(System.IAsyncResult result) {
            return base.Channel.EndRetrieveSocialMediaTypes(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveSocialMediaTypes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService)(this)).BeginRetrieveSocialMediaTypes(callback, asyncState);
        }
        
        private object[] OnEndRetrieveSocialMediaTypes(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaType> retVal = ((IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService)(this)).EndRetrieveSocialMediaTypes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveSocialMediaTypesCompleted(object state) {
            if ((this.RetrieveSocialMediaTypesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveSocialMediaTypesCompleted(this, new RetrieveSocialMediaTypesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveSocialMediaTypesAsync() {
            this.RetrieveSocialMediaTypesAsync(null);
        }
        
        public void RetrieveSocialMediaTypesAsync(object userState) {
            if ((this.onBeginRetrieveSocialMediaTypesDelegate == null)) {
                this.onBeginRetrieveSocialMediaTypesDelegate = new BeginOperationDelegate(this.OnBeginRetrieveSocialMediaTypes);
            }
            if ((this.onEndRetrieveSocialMediaTypesDelegate == null)) {
                this.onEndRetrieveSocialMediaTypesDelegate = new EndOperationDelegate(this.OnEndRetrieveSocialMediaTypes);
            }
            if ((this.onRetrieveSocialMediaTypesCompletedDelegate == null)) {
                this.onRetrieveSocialMediaTypesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveSocialMediaTypesCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveSocialMediaTypesDelegate, null, this.onEndRetrieveSocialMediaTypesDelegate, this.onRetrieveSocialMediaTypesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService.BeginSocialMediaNotificationOptions(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSocialMediaNotificationOptions(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaNotification> IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService.EndSocialMediaNotificationOptions(System.IAsyncResult result) {
            return base.Channel.EndSocialMediaNotificationOptions(result);
        }
        
        private System.IAsyncResult OnBeginSocialMediaNotificationOptions(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService)(this)).BeginSocialMediaNotificationOptions(callback, asyncState);
        }
        
        private object[] OnEndSocialMediaNotificationOptions(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaNotification> retVal = ((IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService)(this)).EndSocialMediaNotificationOptions(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSocialMediaNotificationOptionsCompleted(object state) {
            if ((this.SocialMediaNotificationOptionsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SocialMediaNotificationOptionsCompleted(this, new SocialMediaNotificationOptionsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SocialMediaNotificationOptionsAsync() {
            this.SocialMediaNotificationOptionsAsync(null);
        }
        
        public void SocialMediaNotificationOptionsAsync(object userState) {
            if ((this.onBeginSocialMediaNotificationOptionsDelegate == null)) {
                this.onBeginSocialMediaNotificationOptionsDelegate = new BeginOperationDelegate(this.OnBeginSocialMediaNotificationOptions);
            }
            if ((this.onEndSocialMediaNotificationOptionsDelegate == null)) {
                this.onEndSocialMediaNotificationOptionsDelegate = new EndOperationDelegate(this.OnEndSocialMediaNotificationOptions);
            }
            if ((this.onSocialMediaNotificationOptionsCompletedDelegate == null)) {
                this.onSocialMediaNotificationOptionsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSocialMediaNotificationOptionsCompleted);
            }
            base.InvokeAsync(this.onBeginSocialMediaNotificationOptionsDelegate, null, this.onEndSocialMediaNotificationOptionsDelegate, this.onSocialMediaNotificationOptionsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService CreateChannel() {
            return new SocialMediaServiceClientChannel(this);
        }
        
        private class SocialMediaServiceClientChannel : ChannelBase<IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService>, IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService {
            
            public SocialMediaServiceClientChannel(System.ServiceModel.ClientBase<IndoorWorx.Library.SocialMediaServiceReference.ISocialMediaService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRetrieveSocialMediaTypes(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("RetrieveSocialMediaTypes", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaType> EndRetrieveSocialMediaTypes(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaType> _result = ((System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaType>)(base.EndInvoke("RetrieveSocialMediaTypes", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSocialMediaNotificationOptions(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("SocialMediaNotificationOptions", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaNotification> EndSocialMediaNotificationOptions(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaNotification> _result = ((System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.SocialMediaNotification>)(base.EndInvoke("SocialMediaNotificationOptions", _args, result)));
                return _result;
            }
        }
    }
}
