//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorWorx.MyLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyLibraryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyLibraryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndoorWorx.MyLibrary.Resources.MyLibraryResources", typeof(MyLibraryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new template.
        /// </summary>
        public static string AddNewTemplateHeader {
            get {
                return ResourceManager.GetString("AddNewTemplateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEFORE THE END OF THE INTERVAL.
        /// </summary>
        public static string BeforeTheEndOfTheInterval {
            get {
                return ResourceManager.GetString("BeforeTheEndOfTheInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEFORE THE START OF THE INTERVAL.
        /// </summary>
        public static string BeforeTheStartOfTheInterval {
            get {
                return ResourceManager.GetString("BeforeTheStartOfTheInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN.
        /// </summary>
        public static string BeginButtonText {
            get {
                return ResourceManager.GetString("BeginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COOL DOWN.
        /// </summary>
        public static string CooldownHeader {
            get {
                return ResourceManager.GetString("CooldownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT DOWNS.
        /// </summary>
        public static string CountDownsHeader {
            get {
                return ResourceManager.GetString("CountDownsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT DOWN TO END OF INTERVAL?.
        /// </summary>
        public static string CountDownToEndOfIntervalLabel {
            get {
                return ResourceManager.GetString("CountDownToEndOfIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT DOWN TO START OF INTERVAL?.
        /// </summary>
        public static string CountDownToStartOfIntervalLabel {
            get {
                return ResourceManager.GetString("CountDownToStartOfIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE RIDE.
        /// </summary>
        public static string CreateRideHeader {
            get {
                return ResourceManager.GetString("CreateRideHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a ride from this template..
        /// </summary>
        public static string CreateRideToolTip {
            get {
                return ResourceManager.GetString("CreateRideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new template.
        /// </summary>
        public static string CreateTemplate {
            get {
                return ResourceManager.GetString("CreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE INTERVAL.
        /// </summary>
        public static string DeleteIntervalTitle {
            get {
                return ResourceManager.GetString("DeleteIntervalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete template.
        /// </summary>
        public static string DeleteTemplate {
            get {
                return ResourceManager.GetString("DeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURATION.
        /// </summary>
        public static string DurationLabel {
            get {
                return ResourceManager.GetString("DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT INTERVAL.
        /// </summary>
        public static string EditIntervalTitle {
            get {
                return ResourceManager.GetString("EditIntervalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT TEMPLATE.
        /// </summary>
        public static string EditTemplateHeader {
            get {
                return ResourceManager.GetString("EditTemplateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this template..
        /// </summary>
        public static string EditTemplateToolTip {
            get {
                return ResourceManager.GetString("EditTemplateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFFORT.
        /// </summary>
        public static string EffortLabel {
            get {
                return ResourceManager.GetString("EffortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFFORT TYPE.
        /// </summary>
        public static string EffortTypeLabel {
            get {
                return ResourceManager.GetString("EffortTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW THIS MESSAGE WHEN THE INTERVAL ENDS.
        /// </summary>
        public static string EndOfIntervalMessageLabel {
            get {
                return ResourceManager.GetString("EndOfIntervalMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error removing this template from your library..
        /// </summary>
        public static string ErrorRemovingTemplate {
            get {
                return ResourceManager.GetString("ErrorRemovingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving this template..
        /// </summary>
        public static string ErrorSavingTemplate {
            get {
                return ResourceManager.GetString("ErrorSavingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVERY.
        /// </summary>
        public static string EveryLabel {
            get {
                return ResourceManager.GetString("EveryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM.
        /// </summary>
        public static string FromLabel {
            get {
                return ResourceManager.GetString("FromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string HoursLabel {
            get {
                return ResourceManager.GetString("HoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN MY LIBRARY.
        /// </summary>
        public static string InMyLibrary {
            get {
                return ResourceManager.GetString("InMyLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval has changed. If you continue you will lose all of the changes you have made..
        /// </summary>
        public static string IntervalChangedCancelConfirmation {
            get {
                return ResourceManager.GetString("IntervalChangedCancelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERVALS.
        /// </summary>
        public static string IntervalsLabel {
            get {
                return ResourceManager.GetString("IntervalsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        public static string IntervalTypeLabel {
            get {
                return ResourceManager.GetString("IntervalTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid mode for this view..
        /// </summary>
        public static string InvalidMode {
            get {
                return ResourceManager.GetString("InvalidMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVEL.
        /// </summary>
        public static string LevelLabel {
            get {
                return ResourceManager.GetString("LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN SET.
        /// </summary>
        public static string MainSetHeader {
            get {
                return ResourceManager.GetString("MainSetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string MinutesLabel {
            get {
                return ResourceManager.GetString("MinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW INTERVAL.
        /// </summary>
        public static string NewIntervalTitle {
            get {
                return ResourceManager.GetString("NewIntervalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPEATS.
        /// </summary>
        public static string NumberOfRepeatsLabel {
            get {
                return ResourceManager.GetString("NumberOfRepeatsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} TEMPLATES.
        /// </summary>
        public static string NumberOfTemplatesLabel {
            get {
                return ResourceManager.GetString("NumberOfTemplatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} VIDEOS.
        /// </summary>
        public static string NumberOfVideosLabel {
            get {
                return ResourceManager.GetString("NumberOfVideosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONS.
        /// </summary>
        public static string OptionsLabel {
            get {
                return ResourceManager.GetString("OptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  CREDIT(S) PER RIDE.
        /// </summary>
        public static string PerRide {
            get {
                return ResourceManager.GetString("PerRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIDE VIDEO.
        /// </summary>
        public static string PlayVideo {
            get {
                return ResourceManager.GetString("PlayVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ride video.
        /// </summary>
        public static string PlayVideoTooltip {
            get {
                return ResourceManager.GetString("PlayVideoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preview video.
        /// </summary>
        public static string PreviewVideoTooltip {
            get {
                return ResourceManager.GetString("PreviewVideoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view template.
        /// </summary>
        public static string ReadTemplate {
            get {
                return ResourceManager.GetString("ReadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOVERY.
        /// </summary>
        public static string RecoveryIntervalLabel {
            get {
                return ResourceManager.GetString("RecoveryIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to remove this template from your library?.
        /// </summary>
        public static string RemoveTemplateConfirmation {
            get {
                return ResourceManager.GetString("RemoveTemplateConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE TEMPLATE.
        /// </summary>
        public static string RemoveTemplateHeader {
            get {
                return ResourceManager.GetString("RemoveTemplateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this template from your library..
        /// </summary>
        public static string RemoveTemplateToolTip {
            get {
                return ResourceManager.GetString("RemoveTemplateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string SecondsLabel {
            get {
                return ResourceManager.GetString("SecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIAL MEDIA.
        /// </summary>
        public static string SocialMediaHeader {
            get {
                return ResourceManager.GetString("SocialMediaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW THIS MESSAGE WHEN THE INTERVAL STARTS.
        /// </summary>
        public static string StartOfIntervalMessageLabel {
            get {
                return ResourceManager.GetString("StartOfIntervalMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template has changed. If you continue you will lose all of the changes you have made..
        /// </summary>
        public static string TemplateChangedCancelConfirmation {
            get {
                return ResourceManager.GetString("TemplateChangedCancelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPLATES.
        /// </summary>
        public static string TemplatesTitle {
            get {
                return ResourceManager.GetString("TemplatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT MESSAGES.
        /// </summary>
        public static string TextMessagesHeader {
            get {
                return ResourceManager.GetString("TextMessagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAMS.
        /// </summary>
        public static string TrainingProgramsTitle {
            get {
                return ResourceManager.GetString("TrainingProgramsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit template.
        /// </summary>
        public static string UpdateTemplate {
            get {
                return ResourceManager.GetString("UpdateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEOS.
        /// </summary>
        public static string VideosTitle {
            get {
                return ResourceManager.GetString("VideosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW INTERVAL.
        /// </summary>
        public static string ViewIntervalTitle {
            get {
                return ResourceManager.GetString("ViewIntervalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARM UP.
        /// </summary>
        public static string WarmupHeader {
            get {
                return ResourceManager.GetString("WarmupHeader", resourceCulture);
            }
        }
    }
}
