//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorWorx.MyLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyLibraryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyLibraryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndoorWorx.MyLibrary.Resources.MyLibraryResources", typeof(MyLibraryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN MY LIBRARY.
        /// </summary>
        public static string InMyLibrary {
            get {
                return ResourceManager.GetString("InMyLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} TEMPLATES.
        /// </summary>
        public static string NumberOfTemplatesLabel {
            get {
                return ResourceManager.GetString("NumberOfTemplatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} VIDEOS.
        /// </summary>
        public static string NumberOfVideosLabel {
            get {
                return ResourceManager.GetString("NumberOfVideosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayVideo {
            get {
                return ResourceManager.GetString("PlayVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPLATES.
        /// </summary>
        public static string TemplatesTitle {
            get {
                return ResourceManager.GetString("TemplatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAMS.
        /// </summary>
        public static string TrainingProgramsTitle {
            get {
                return ResourceManager.GetString("TrainingProgramsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEOS.
        /// </summary>
        public static string VideosTitle {
            get {
                return ResourceManager.GetString("VideosTitle", resourceCulture);
            }
        }
    }
}
