//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorWorx.Catalog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CatalogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatalogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndoorWorx.Catalog.Resources.CatalogResources", typeof(CatalogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to My Library.
        /// </summary>
        public static string AddToMyLibraryHeader {
            get {
                return ResourceManager.GetString("AddToMyLibraryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Power:.
        /// </summary>
        public static string AveragePowerLabel {
            get {
                return ResourceManager.GetString("AveragePowerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY CATALOG.
        /// </summary>
        public static string ByCatalog {
            get {
                return ResourceManager.GetString("ByCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY CATEGORY.
        /// </summary>
        public static string ByCategory {
            get {
                return ResourceManager.GetString("ByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY GENRE.
        /// </summary>
        public static string ByGenre {
            get {
                return ResourceManager.GetString("ByGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY TITLE.
        /// </summary>
        public static string ByTitle {
            get {
                return ResourceManager.GetString("ByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATALOG.
        /// </summary>
        public static string CatalogPaneTitle {
            get {
                return ResourceManager.GetString("CatalogPaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} CREDITS.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionTitle {
            get {
                return ResourceManager.GetString("DescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string DesignButtonText {
            get {
                return ResourceManager.GetString("DesignButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design a new training set using this training set as the basis for it..
        /// </summary>
        public static string DesignTrainingSetToolTip {
            get {
                return ResourceManager.GetString("DesignTrainingSetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have insufficient credits to use this video. Please purchase more credits..
        /// </summary>
        public static string InsufficientCredits {
            get {
                return ResourceManager.GetString("InsufficientCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity Factor (IF):.
        /// </summary>
        public static string IntensityFactorLabel {
            get {
                return ResourceManager.GetString("IntensityFactorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading media ....
        /// </summary>
        public static string LoadingMediaProgressMessage {
            get {
                return ResourceManager.GetString("LoadingMediaProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading telemetry ....
        /// </summary>
        public static string LoadingTelemetryProgressMessage {
            get {
                return ResourceManager.GetString("LoadingTelemetryProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag items to My Library of Templates.
        /// </summary>
        public static string MyLibraryOfTemplates {
            get {
                return ResourceManager.GetString("MyLibraryOfTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag items to My Library of Videos.
        /// </summary>
        public static string MyLibraryOfVideos {
            get {
                return ResourceManager.GetString("MyLibraryOfVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized Power (NP):.
        /// </summary>
        public static string NormalizedPowerLabel {
            get {
                return ResourceManager.GetString("NormalizedPowerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} TEMPLATES.
        /// </summary>
        public static string NumberOfTemplatesLabel {
            get {
                return ResourceManager.GetString("NumberOfTemplatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} VIDEOS.
        /// </summary>
        public static string NumberOfVideosLabel {
            get {
                return ResourceManager.GetString("NumberOfVideosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the preview of this video.
        /// </summary>
        public static string PauseButtonTooltip {
            get {
                return ResourceManager.GetString("PauseButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayButtonText {
            get {
                return ResourceManager.GetString("PlayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview this video.
        /// </summary>
        public static string PlayButtonTooltip {
            get {
                return ResourceManager.GetString("PlayButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play this training set..
        /// </summary>
        public static string PlayTrainingSetToolTip {
            get {
                return ResourceManager.GetString("PlayTrainingSetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewButtonText {
            get {
                return ResourceManager.GetString("PreviewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewTitle {
            get {
                return ResourceManager.GetString("PreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview this training set..
        /// </summary>
        public static string PreviewTrainingSetToolTip {
            get {
                return ResourceManager.GetString("PreviewTrainingSetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Video.
        /// </summary>
        public static string PreviewVideoHeader {
            get {
                return ResourceManager.GetString("PreviewVideoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the profiles for the selected training set..
        /// </summary>
        public static string ProfilesDescription {
            get {
                return ResourceManager.GetString("ProfilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string ProfilesTitle {
            get {
                return ResourceManager.GetString("ProfilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the reviews from other riders of the selected training set..
        /// </summary>
        public static string ReviewsDescription {
            get {
                return ResourceManager.GetString("ReviewsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string ReviewsTitle {
            get {
                return ResourceManager.GetString("ReviewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIDES.
        /// </summary>
        public static string RidesTitle {
            get {
                return ResourceManager.GetString("RidesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPLATES.
        /// </summary>
        public static string TemplatesTitle {
            get {
                return ResourceManager.GetString("TemplatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Metrics.
        /// </summary>
        public static string TrainingMetricsTitle {
            get {
                return ResourceManager.GetString("TrainingMetricsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAMS.
        /// </summary>
        public static string TrainingProgramsTitle {
            get {
                return ResourceManager.GetString("TrainingProgramsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Sets.
        /// </summary>
        public static string TrainingSetsTitle {
            get {
                return ResourceManager.GetString("TrainingSetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variability Index (VI):.
        /// </summary>
        public static string VariabilityIndexLabel {
            get {
                return ResourceManager.GetString("VariabilityIndexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already added the selected video to your library..
        /// </summary>
        public static string VideoAlreadyAdded {
            get {
                return ResourceManager.GetString("VideoAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEOS.
        /// </summary>
        public static string VideosTitle {
            get {
                return ResourceManager.GetString("VideosTitle", resourceCulture);
            }
        }
    }
}
