//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.60310.0
// 
namespace IndoorWorx.Library.ApplicationUserServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationUserFindCriteria", Namespace="http://schemas.datacontract.org/2004/07/IndoorWorx.Infrastructure.Criteria", IsReference=true)]
    public partial class ApplicationUserFindCriteria : IndoorWorx.Infrastructure.Models.BaseModel, System.ComponentModel.INotifyPropertyChanged {
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApplicationUserServiceReference.IApplicationUserService")]
    public interface IApplicationUserService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IApplicationUserService/SaveApplicationUser", ReplyAction="http://tempuri.org/IApplicationUserService/SaveApplicationUserResponse")]
        System.IAsyncResult BeginSaveApplicationUser(IndoorWorx.Infrastructure.Models.ApplicationUser user, System.AsyncCallback callback, object asyncState);
        
        IndoorWorx.Infrastructure.Models.ApplicationUser EndSaveApplicationUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IApplicationUserService/RetrieveApplicationUser", ReplyAction="http://tempuri.org/IApplicationUserService/RetrieveApplicationUserResponse")]
        System.IAsyncResult BeginRetrieveApplicationUser(IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria criteria, System.AsyncCallback callback, object asyncState);
        
        IndoorWorx.Infrastructure.Models.ApplicationUser EndRetrieveApplicationUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IApplicationUserService/RetrieveAllOccupations", ReplyAction="http://tempuri.org/IApplicationUserService/RetrieveAllOccupationsResponse")]
        System.IAsyncResult BeginRetrieveAllOccupations(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.Occupation> EndRetrieveAllOccupations(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IApplicationUserService/RetrieveAllReferralSources", ReplyAction="http://tempuri.org/IApplicationUserService/RetrieveAllReferralSourcesResponse")]
        System.IAsyncResult BeginRetrieveAllReferralSources(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.ReferralSource> EndRetrieveAllReferralSources(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IApplicationUserService/AddVideoToLibrary", ReplyAction="http://tempuri.org/IApplicationUserService/AddVideoToLibraryResponse")]
        System.IAsyncResult BeginAddVideoToLibrary(IndoorWorx.Infrastructure.Requests.AddVideoRequest request, System.AsyncCallback callback, object asyncState);
        
        IndoorWorx.Infrastructure.Responses.AddVideoResponse EndAddVideoToLibrary(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IApplicationUserService/AddTemplateToLibrary", ReplyAction="http://tempuri.org/IApplicationUserService/AddTemplateToLibraryResponse")]
        System.IAsyncResult BeginAddTemplateToLibrary(IndoorWorx.Infrastructure.Requests.AddTemplateRequest request, System.AsyncCallback callback, object asyncState);
        
        IndoorWorx.Infrastructure.Responses.AddTemplateResponse EndAddTemplateToLibrary(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IApplicationUserService/PlayVideo", ReplyAction="http://tempuri.org/IApplicationUserService/PlayVideoResponse")]
        System.IAsyncResult BeginPlayVideo(IndoorWorx.Infrastructure.Requests.PlayVideoRequest request, System.AsyncCallback callback, object asyncState);
        
        IndoorWorx.Infrastructure.Responses.PlayVideoResponse EndPlayVideo(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplicationUserServiceChannel : IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveApplicationUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveApplicationUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndoorWorx.Infrastructure.Models.ApplicationUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndoorWorx.Infrastructure.Models.ApplicationUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveApplicationUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveApplicationUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndoorWorx.Infrastructure.Models.ApplicationUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndoorWorx.Infrastructure.Models.ApplicationUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveAllOccupationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveAllOccupationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.Occupation> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.Occupation>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveAllReferralSourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveAllReferralSourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.ReferralSource> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.ReferralSource>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddVideoToLibraryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddVideoToLibraryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndoorWorx.Infrastructure.Responses.AddVideoResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndoorWorx.Infrastructure.Responses.AddVideoResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddTemplateToLibraryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddTemplateToLibraryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndoorWorx.Infrastructure.Responses.AddTemplateResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndoorWorx.Infrastructure.Responses.AddTemplateResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayVideoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PlayVideoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndoorWorx.Infrastructure.Responses.PlayVideoResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndoorWorx.Infrastructure.Responses.PlayVideoResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationUserServiceClient : System.ServiceModel.ClientBase<IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService>, IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService {
        
        private BeginOperationDelegate onBeginSaveApplicationUserDelegate;
        
        private EndOperationDelegate onEndSaveApplicationUserDelegate;
        
        private System.Threading.SendOrPostCallback onSaveApplicationUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveApplicationUserDelegate;
        
        private EndOperationDelegate onEndRetrieveApplicationUserDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveApplicationUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveAllOccupationsDelegate;
        
        private EndOperationDelegate onEndRetrieveAllOccupationsDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveAllOccupationsCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveAllReferralSourcesDelegate;
        
        private EndOperationDelegate onEndRetrieveAllReferralSourcesDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveAllReferralSourcesCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddVideoToLibraryDelegate;
        
        private EndOperationDelegate onEndAddVideoToLibraryDelegate;
        
        private System.Threading.SendOrPostCallback onAddVideoToLibraryCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddTemplateToLibraryDelegate;
        
        private EndOperationDelegate onEndAddTemplateToLibraryDelegate;
        
        private System.Threading.SendOrPostCallback onAddTemplateToLibraryCompletedDelegate;
        
        private BeginOperationDelegate onBeginPlayVideoDelegate;
        
        private EndOperationDelegate onEndPlayVideoDelegate;
        
        private System.Threading.SendOrPostCallback onPlayVideoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ApplicationUserServiceClient() {
        }
        
        public ApplicationUserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationUserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationUserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationUserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<SaveApplicationUserCompletedEventArgs> SaveApplicationUserCompleted;
        
        public event System.EventHandler<RetrieveApplicationUserCompletedEventArgs> RetrieveApplicationUserCompleted;
        
        public event System.EventHandler<RetrieveAllOccupationsCompletedEventArgs> RetrieveAllOccupationsCompleted;
        
        public event System.EventHandler<RetrieveAllReferralSourcesCompletedEventArgs> RetrieveAllReferralSourcesCompleted;
        
        public event System.EventHandler<AddVideoToLibraryCompletedEventArgs> AddVideoToLibraryCompleted;
        
        public event System.EventHandler<AddTemplateToLibraryCompletedEventArgs> AddTemplateToLibraryCompleted;
        
        public event System.EventHandler<PlayVideoCompletedEventArgs> PlayVideoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.BeginSaveApplicationUser(IndoorWorx.Infrastructure.Models.ApplicationUser user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveApplicationUser(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndoorWorx.Infrastructure.Models.ApplicationUser IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.EndSaveApplicationUser(System.IAsyncResult result) {
            return base.Channel.EndSaveApplicationUser(result);
        }
        
        private System.IAsyncResult OnBeginSaveApplicationUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            IndoorWorx.Infrastructure.Models.ApplicationUser user = ((IndoorWorx.Infrastructure.Models.ApplicationUser)(inValues[0]));
            return ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).BeginSaveApplicationUser(user, callback, asyncState);
        }
        
        private object[] OnEndSaveApplicationUser(System.IAsyncResult result) {
            IndoorWorx.Infrastructure.Models.ApplicationUser retVal = ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).EndSaveApplicationUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveApplicationUserCompleted(object state) {
            if ((this.SaveApplicationUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveApplicationUserCompleted(this, new SaveApplicationUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveApplicationUserAsync(IndoorWorx.Infrastructure.Models.ApplicationUser user) {
            this.SaveApplicationUserAsync(user, null);
        }
        
        public void SaveApplicationUserAsync(IndoorWorx.Infrastructure.Models.ApplicationUser user, object userState) {
            if ((this.onBeginSaveApplicationUserDelegate == null)) {
                this.onBeginSaveApplicationUserDelegate = new BeginOperationDelegate(this.OnBeginSaveApplicationUser);
            }
            if ((this.onEndSaveApplicationUserDelegate == null)) {
                this.onEndSaveApplicationUserDelegate = new EndOperationDelegate(this.OnEndSaveApplicationUser);
            }
            if ((this.onSaveApplicationUserCompletedDelegate == null)) {
                this.onSaveApplicationUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveApplicationUserCompleted);
            }
            base.InvokeAsync(this.onBeginSaveApplicationUserDelegate, new object[] {
                        user}, this.onEndSaveApplicationUserDelegate, this.onSaveApplicationUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.BeginRetrieveApplicationUser(IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria criteria, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveApplicationUser(criteria, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndoorWorx.Infrastructure.Models.ApplicationUser IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.EndRetrieveApplicationUser(System.IAsyncResult result) {
            return base.Channel.EndRetrieveApplicationUser(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveApplicationUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria criteria = ((IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria)(inValues[0]));
            return ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).BeginRetrieveApplicationUser(criteria, callback, asyncState);
        }
        
        private object[] OnEndRetrieveApplicationUser(System.IAsyncResult result) {
            IndoorWorx.Infrastructure.Models.ApplicationUser retVal = ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).EndRetrieveApplicationUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveApplicationUserCompleted(object state) {
            if ((this.RetrieveApplicationUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveApplicationUserCompleted(this, new RetrieveApplicationUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveApplicationUserAsync(IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria criteria) {
            this.RetrieveApplicationUserAsync(criteria, null);
        }
        
        public void RetrieveApplicationUserAsync(IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria criteria, object userState) {
            if ((this.onBeginRetrieveApplicationUserDelegate == null)) {
                this.onBeginRetrieveApplicationUserDelegate = new BeginOperationDelegate(this.OnBeginRetrieveApplicationUser);
            }
            if ((this.onEndRetrieveApplicationUserDelegate == null)) {
                this.onEndRetrieveApplicationUserDelegate = new EndOperationDelegate(this.OnEndRetrieveApplicationUser);
            }
            if ((this.onRetrieveApplicationUserCompletedDelegate == null)) {
                this.onRetrieveApplicationUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveApplicationUserCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveApplicationUserDelegate, new object[] {
                        criteria}, this.onEndRetrieveApplicationUserDelegate, this.onRetrieveApplicationUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.BeginRetrieveAllOccupations(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveAllOccupations(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.Occupation> IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.EndRetrieveAllOccupations(System.IAsyncResult result) {
            return base.Channel.EndRetrieveAllOccupations(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveAllOccupations(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).BeginRetrieveAllOccupations(callback, asyncState);
        }
        
        private object[] OnEndRetrieveAllOccupations(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.Occupation> retVal = ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).EndRetrieveAllOccupations(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveAllOccupationsCompleted(object state) {
            if ((this.RetrieveAllOccupationsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveAllOccupationsCompleted(this, new RetrieveAllOccupationsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveAllOccupationsAsync() {
            this.RetrieveAllOccupationsAsync(null);
        }
        
        public void RetrieveAllOccupationsAsync(object userState) {
            if ((this.onBeginRetrieveAllOccupationsDelegate == null)) {
                this.onBeginRetrieveAllOccupationsDelegate = new BeginOperationDelegate(this.OnBeginRetrieveAllOccupations);
            }
            if ((this.onEndRetrieveAllOccupationsDelegate == null)) {
                this.onEndRetrieveAllOccupationsDelegate = new EndOperationDelegate(this.OnEndRetrieveAllOccupations);
            }
            if ((this.onRetrieveAllOccupationsCompletedDelegate == null)) {
                this.onRetrieveAllOccupationsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveAllOccupationsCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveAllOccupationsDelegate, null, this.onEndRetrieveAllOccupationsDelegate, this.onRetrieveAllOccupationsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.BeginRetrieveAllReferralSources(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveAllReferralSources(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.ReferralSource> IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.EndRetrieveAllReferralSources(System.IAsyncResult result) {
            return base.Channel.EndRetrieveAllReferralSources(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveAllReferralSources(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).BeginRetrieveAllReferralSources(callback, asyncState);
        }
        
        private object[] OnEndRetrieveAllReferralSources(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.ReferralSource> retVal = ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).EndRetrieveAllReferralSources(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveAllReferralSourcesCompleted(object state) {
            if ((this.RetrieveAllReferralSourcesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveAllReferralSourcesCompleted(this, new RetrieveAllReferralSourcesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveAllReferralSourcesAsync() {
            this.RetrieveAllReferralSourcesAsync(null);
        }
        
        public void RetrieveAllReferralSourcesAsync(object userState) {
            if ((this.onBeginRetrieveAllReferralSourcesDelegate == null)) {
                this.onBeginRetrieveAllReferralSourcesDelegate = new BeginOperationDelegate(this.OnBeginRetrieveAllReferralSources);
            }
            if ((this.onEndRetrieveAllReferralSourcesDelegate == null)) {
                this.onEndRetrieveAllReferralSourcesDelegate = new EndOperationDelegate(this.OnEndRetrieveAllReferralSources);
            }
            if ((this.onRetrieveAllReferralSourcesCompletedDelegate == null)) {
                this.onRetrieveAllReferralSourcesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveAllReferralSourcesCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveAllReferralSourcesDelegate, null, this.onEndRetrieveAllReferralSourcesDelegate, this.onRetrieveAllReferralSourcesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.BeginAddVideoToLibrary(IndoorWorx.Infrastructure.Requests.AddVideoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddVideoToLibrary(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndoorWorx.Infrastructure.Responses.AddVideoResponse IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.EndAddVideoToLibrary(System.IAsyncResult result) {
            return base.Channel.EndAddVideoToLibrary(result);
        }
        
        private System.IAsyncResult OnBeginAddVideoToLibrary(object[] inValues, System.AsyncCallback callback, object asyncState) {
            IndoorWorx.Infrastructure.Requests.AddVideoRequest request = ((IndoorWorx.Infrastructure.Requests.AddVideoRequest)(inValues[0]));
            return ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).BeginAddVideoToLibrary(request, callback, asyncState);
        }
        
        private object[] OnEndAddVideoToLibrary(System.IAsyncResult result) {
            IndoorWorx.Infrastructure.Responses.AddVideoResponse retVal = ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).EndAddVideoToLibrary(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddVideoToLibraryCompleted(object state) {
            if ((this.AddVideoToLibraryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddVideoToLibraryCompleted(this, new AddVideoToLibraryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddVideoToLibraryAsync(IndoorWorx.Infrastructure.Requests.AddVideoRequest request) {
            this.AddVideoToLibraryAsync(request, null);
        }
        
        public void AddVideoToLibraryAsync(IndoorWorx.Infrastructure.Requests.AddVideoRequest request, object userState) {
            if ((this.onBeginAddVideoToLibraryDelegate == null)) {
                this.onBeginAddVideoToLibraryDelegate = new BeginOperationDelegate(this.OnBeginAddVideoToLibrary);
            }
            if ((this.onEndAddVideoToLibraryDelegate == null)) {
                this.onEndAddVideoToLibraryDelegate = new EndOperationDelegate(this.OnEndAddVideoToLibrary);
            }
            if ((this.onAddVideoToLibraryCompletedDelegate == null)) {
                this.onAddVideoToLibraryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddVideoToLibraryCompleted);
            }
            base.InvokeAsync(this.onBeginAddVideoToLibraryDelegate, new object[] {
                        request}, this.onEndAddVideoToLibraryDelegate, this.onAddVideoToLibraryCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.BeginAddTemplateToLibrary(IndoorWorx.Infrastructure.Requests.AddTemplateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddTemplateToLibrary(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndoorWorx.Infrastructure.Responses.AddTemplateResponse IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.EndAddTemplateToLibrary(System.IAsyncResult result) {
            return base.Channel.EndAddTemplateToLibrary(result);
        }
        
        private System.IAsyncResult OnBeginAddTemplateToLibrary(object[] inValues, System.AsyncCallback callback, object asyncState) {
            IndoorWorx.Infrastructure.Requests.AddTemplateRequest request = ((IndoorWorx.Infrastructure.Requests.AddTemplateRequest)(inValues[0]));
            return ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).BeginAddTemplateToLibrary(request, callback, asyncState);
        }
        
        private object[] OnEndAddTemplateToLibrary(System.IAsyncResult result) {
            IndoorWorx.Infrastructure.Responses.AddTemplateResponse retVal = ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).EndAddTemplateToLibrary(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddTemplateToLibraryCompleted(object state) {
            if ((this.AddTemplateToLibraryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddTemplateToLibraryCompleted(this, new AddTemplateToLibraryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddTemplateToLibraryAsync(IndoorWorx.Infrastructure.Requests.AddTemplateRequest request) {
            this.AddTemplateToLibraryAsync(request, null);
        }
        
        public void AddTemplateToLibraryAsync(IndoorWorx.Infrastructure.Requests.AddTemplateRequest request, object userState) {
            if ((this.onBeginAddTemplateToLibraryDelegate == null)) {
                this.onBeginAddTemplateToLibraryDelegate = new BeginOperationDelegate(this.OnBeginAddTemplateToLibrary);
            }
            if ((this.onEndAddTemplateToLibraryDelegate == null)) {
                this.onEndAddTemplateToLibraryDelegate = new EndOperationDelegate(this.OnEndAddTemplateToLibrary);
            }
            if ((this.onAddTemplateToLibraryCompletedDelegate == null)) {
                this.onAddTemplateToLibraryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddTemplateToLibraryCompleted);
            }
            base.InvokeAsync(this.onBeginAddTemplateToLibraryDelegate, new object[] {
                        request}, this.onEndAddTemplateToLibraryDelegate, this.onAddTemplateToLibraryCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.BeginPlayVideo(IndoorWorx.Infrastructure.Requests.PlayVideoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPlayVideo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndoorWorx.Infrastructure.Responses.PlayVideoResponse IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.EndPlayVideo(System.IAsyncResult result) {
            return base.Channel.EndPlayVideo(result);
        }
        
        private System.IAsyncResult OnBeginPlayVideo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            IndoorWorx.Infrastructure.Requests.PlayVideoRequest request = ((IndoorWorx.Infrastructure.Requests.PlayVideoRequest)(inValues[0]));
            return ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).BeginPlayVideo(request, callback, asyncState);
        }
        
        private object[] OnEndPlayVideo(System.IAsyncResult result) {
            IndoorWorx.Infrastructure.Responses.PlayVideoResponse retVal = ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).EndPlayVideo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPlayVideoCompleted(object state) {
            if ((this.PlayVideoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PlayVideoCompleted(this, new PlayVideoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PlayVideoAsync(IndoorWorx.Infrastructure.Requests.PlayVideoRequest request) {
            this.PlayVideoAsync(request, null);
        }
        
        public void PlayVideoAsync(IndoorWorx.Infrastructure.Requests.PlayVideoRequest request, object userState) {
            if ((this.onBeginPlayVideoDelegate == null)) {
                this.onBeginPlayVideoDelegate = new BeginOperationDelegate(this.OnBeginPlayVideo);
            }
            if ((this.onEndPlayVideoDelegate == null)) {
                this.onEndPlayVideoDelegate = new EndOperationDelegate(this.OnEndPlayVideo);
            }
            if ((this.onPlayVideoCompletedDelegate == null)) {
                this.onPlayVideoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPlayVideoCompleted);
            }
            base.InvokeAsync(this.onBeginPlayVideoDelegate, new object[] {
                        request}, this.onEndPlayVideoDelegate, this.onPlayVideoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService CreateChannel() {
            return new ApplicationUserServiceClientChannel(this);
        }
        
        private class ApplicationUserServiceClientChannel : ChannelBase<IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService>, IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService {
            
            public ApplicationUserServiceClientChannel(System.ServiceModel.ClientBase<IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSaveApplicationUser(IndoorWorx.Infrastructure.Models.ApplicationUser user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("SaveApplicationUser", _args, callback, asyncState);
                return _result;
            }
            
            public IndoorWorx.Infrastructure.Models.ApplicationUser EndSaveApplicationUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                IndoorWorx.Infrastructure.Models.ApplicationUser _result = ((IndoorWorx.Infrastructure.Models.ApplicationUser)(base.EndInvoke("SaveApplicationUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveApplicationUser(IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria criteria, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = criteria;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveApplicationUser", _args, callback, asyncState);
                return _result;
            }
            
            public IndoorWorx.Infrastructure.Models.ApplicationUser EndRetrieveApplicationUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                IndoorWorx.Infrastructure.Models.ApplicationUser _result = ((IndoorWorx.Infrastructure.Models.ApplicationUser)(base.EndInvoke("RetrieveApplicationUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveAllOccupations(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("RetrieveAllOccupations", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.Occupation> EndRetrieveAllOccupations(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.Occupation> _result = ((System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.Occupation>)(base.EndInvoke("RetrieveAllOccupations", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveAllReferralSources(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("RetrieveAllReferralSources", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.ReferralSource> EndRetrieveAllReferralSources(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.ReferralSource> _result = ((System.Collections.ObjectModel.ObservableCollection<IndoorWorx.Infrastructure.Models.ReferralSource>)(base.EndInvoke("RetrieveAllReferralSources", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddVideoToLibrary(IndoorWorx.Infrastructure.Requests.AddVideoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AddVideoToLibrary", _args, callback, asyncState);
                return _result;
            }
            
            public IndoorWorx.Infrastructure.Responses.AddVideoResponse EndAddVideoToLibrary(System.IAsyncResult result) {
                object[] _args = new object[0];
                IndoorWorx.Infrastructure.Responses.AddVideoResponse _result = ((IndoorWorx.Infrastructure.Responses.AddVideoResponse)(base.EndInvoke("AddVideoToLibrary", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddTemplateToLibrary(IndoorWorx.Infrastructure.Requests.AddTemplateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AddTemplateToLibrary", _args, callback, asyncState);
                return _result;
            }
            
            public IndoorWorx.Infrastructure.Responses.AddTemplateResponse EndAddTemplateToLibrary(System.IAsyncResult result) {
                object[] _args = new object[0];
                IndoorWorx.Infrastructure.Responses.AddTemplateResponse _result = ((IndoorWorx.Infrastructure.Responses.AddTemplateResponse)(base.EndInvoke("AddTemplateToLibrary", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPlayVideo(IndoorWorx.Infrastructure.Requests.PlayVideoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("PlayVideo", _args, callback, asyncState);
                return _result;
            }
            
            public IndoorWorx.Infrastructure.Responses.PlayVideoResponse EndPlayVideo(System.IAsyncResult result) {
                object[] _args = new object[0];
                IndoorWorx.Infrastructure.Responses.PlayVideoResponse _result = ((IndoorWorx.Infrastructure.Responses.PlayVideoResponse)(base.EndInvoke("PlayVideo", _args, result)));
                return _result;
            }
        }
    }
}
