//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace IndoorWorx.Library.ApplicationUserServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationUserFindCriteria", Namespace="http://schemas.datacontract.org/2004/07/IndoorWorx.Infrastructure.Criteria", IsReference=true)]
    public partial class ApplicationUserFindCriteria : IndoorWorx.Infrastructure.Models.BaseModel, System.ComponentModel.INotifyPropertyChanged {
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApplicationUserServiceReference.IApplicationUserService")]
    public interface IApplicationUserService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IApplicationUserService/SaveApplicationUser", ReplyAction="http://tempuri.org/IApplicationUserService/SaveApplicationUserResponse")]
        System.IAsyncResult BeginSaveApplicationUser(IndoorWorx.Infrastructure.Models.ApplicationUser user, System.AsyncCallback callback, object asyncState);
        
        IndoorWorx.Infrastructure.Models.ApplicationUser EndSaveApplicationUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IApplicationUserService/RetrieveApplicationUser", ReplyAction="http://tempuri.org/IApplicationUserService/RetrieveApplicationUserResponse")]
        System.IAsyncResult BeginRetrieveApplicationUser(IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria criteria, System.AsyncCallback callback, object asyncState);
        
        IndoorWorx.Infrastructure.Models.ApplicationUser EndRetrieveApplicationUser(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplicationUserServiceChannel : IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveApplicationUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveApplicationUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndoorWorx.Infrastructure.Models.ApplicationUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndoorWorx.Infrastructure.Models.ApplicationUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveApplicationUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveApplicationUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndoorWorx.Infrastructure.Models.ApplicationUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndoorWorx.Infrastructure.Models.ApplicationUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationUserServiceClient : System.ServiceModel.ClientBase<IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService>, IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService {
        
        private BeginOperationDelegate onBeginSaveApplicationUserDelegate;
        
        private EndOperationDelegate onEndSaveApplicationUserDelegate;
        
        private System.Threading.SendOrPostCallback onSaveApplicationUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveApplicationUserDelegate;
        
        private EndOperationDelegate onEndRetrieveApplicationUserDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveApplicationUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ApplicationUserServiceClient() {
        }
        
        public ApplicationUserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationUserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationUserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationUserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<SaveApplicationUserCompletedEventArgs> SaveApplicationUserCompleted;
        
        public event System.EventHandler<RetrieveApplicationUserCompletedEventArgs> RetrieveApplicationUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.BeginSaveApplicationUser(IndoorWorx.Infrastructure.Models.ApplicationUser user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveApplicationUser(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndoorWorx.Infrastructure.Models.ApplicationUser IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.EndSaveApplicationUser(System.IAsyncResult result) {
            return base.Channel.EndSaveApplicationUser(result);
        }
        
        private System.IAsyncResult OnBeginSaveApplicationUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            IndoorWorx.Infrastructure.Models.ApplicationUser user = ((IndoorWorx.Infrastructure.Models.ApplicationUser)(inValues[0]));
            return ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).BeginSaveApplicationUser(user, callback, asyncState);
        }
        
        private object[] OnEndSaveApplicationUser(System.IAsyncResult result) {
            IndoorWorx.Infrastructure.Models.ApplicationUser retVal = ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).EndSaveApplicationUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveApplicationUserCompleted(object state) {
            if ((this.SaveApplicationUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveApplicationUserCompleted(this, new SaveApplicationUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveApplicationUserAsync(IndoorWorx.Infrastructure.Models.ApplicationUser user) {
            this.SaveApplicationUserAsync(user, null);
        }
        
        public void SaveApplicationUserAsync(IndoorWorx.Infrastructure.Models.ApplicationUser user, object userState) {
            if ((this.onBeginSaveApplicationUserDelegate == null)) {
                this.onBeginSaveApplicationUserDelegate = new BeginOperationDelegate(this.OnBeginSaveApplicationUser);
            }
            if ((this.onEndSaveApplicationUserDelegate == null)) {
                this.onEndSaveApplicationUserDelegate = new EndOperationDelegate(this.OnEndSaveApplicationUser);
            }
            if ((this.onSaveApplicationUserCompletedDelegate == null)) {
                this.onSaveApplicationUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveApplicationUserCompleted);
            }
            base.InvokeAsync(this.onBeginSaveApplicationUserDelegate, new object[] {
                        user}, this.onEndSaveApplicationUserDelegate, this.onSaveApplicationUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.BeginRetrieveApplicationUser(IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria criteria, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveApplicationUser(criteria, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndoorWorx.Infrastructure.Models.ApplicationUser IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService.EndRetrieveApplicationUser(System.IAsyncResult result) {
            return base.Channel.EndRetrieveApplicationUser(result);
        }
        
        private System.IAsyncResult OnBeginRetrieveApplicationUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria criteria = ((IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria)(inValues[0]));
            return ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).BeginRetrieveApplicationUser(criteria, callback, asyncState);
        }
        
        private object[] OnEndRetrieveApplicationUser(System.IAsyncResult result) {
            IndoorWorx.Infrastructure.Models.ApplicationUser retVal = ((IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService)(this)).EndRetrieveApplicationUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveApplicationUserCompleted(object state) {
            if ((this.RetrieveApplicationUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveApplicationUserCompleted(this, new RetrieveApplicationUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveApplicationUserAsync(IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria criteria) {
            this.RetrieveApplicationUserAsync(criteria, null);
        }
        
        public void RetrieveApplicationUserAsync(IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria criteria, object userState) {
            if ((this.onBeginRetrieveApplicationUserDelegate == null)) {
                this.onBeginRetrieveApplicationUserDelegate = new BeginOperationDelegate(this.OnBeginRetrieveApplicationUser);
            }
            if ((this.onEndRetrieveApplicationUserDelegate == null)) {
                this.onEndRetrieveApplicationUserDelegate = new EndOperationDelegate(this.OnEndRetrieveApplicationUser);
            }
            if ((this.onRetrieveApplicationUserCompletedDelegate == null)) {
                this.onRetrieveApplicationUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveApplicationUserCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveApplicationUserDelegate, new object[] {
                        criteria}, this.onEndRetrieveApplicationUserDelegate, this.onRetrieveApplicationUserCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService CreateChannel() {
            return new ApplicationUserServiceClientChannel(this);
        }
        
        private class ApplicationUserServiceClientChannel : ChannelBase<IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService>, IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService {
            
            public ApplicationUserServiceClientChannel(System.ServiceModel.ClientBase<IndoorWorx.Library.ApplicationUserServiceReference.IApplicationUserService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSaveApplicationUser(IndoorWorx.Infrastructure.Models.ApplicationUser user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("SaveApplicationUser", _args, callback, asyncState);
                return _result;
            }
            
            public IndoorWorx.Infrastructure.Models.ApplicationUser EndSaveApplicationUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                IndoorWorx.Infrastructure.Models.ApplicationUser _result = ((IndoorWorx.Infrastructure.Models.ApplicationUser)(base.EndInvoke("SaveApplicationUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveApplicationUser(IndoorWorx.Library.ApplicationUserServiceReference.ApplicationUserFindCriteria criteria, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = criteria;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveApplicationUser", _args, callback, asyncState);
                return _result;
            }
            
            public IndoorWorx.Infrastructure.Models.ApplicationUser EndRetrieveApplicationUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                IndoorWorx.Infrastructure.Models.ApplicationUser _result = ((IndoorWorx.Infrastructure.Models.ApplicationUser)(base.EndInvoke("RetrieveApplicationUser", _args, result)));
                return _result;
            }
        }
    }
}
